default_window_width = 700
min_content_height = 0
max_content_height = 400
name_match_highlight_color = "orange"
decorate_window = false
close_window_on_losing_focus = false
query_placeholder = "Search"
icon_size = 32
entry_icon = "search"
toggle_key = "<Win>space"
min_score = 5
result_size = 5

[plugins]
