# What shell to use?
shell = "fish"

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Hack Nerd Font Mono"

[window]
padding = { x = 15, y = 15 }
dynamic_padding = false
opacity = 1

[window.dimensions]
columns = 128
lines = 32

[selection]
save_to_clipboard = true
